Index/urls.py
#!/usr/bin/env python

# -*- encoding: utf-8 -*-

'''
@Author  :   Zhuang_Qingyao
 
@Contact :   qyzhg@163.com
 
@File    :   urls.py
 
@Time    :   2020/5/20 10:23 上午
'''


from django.urls import path

from Index import views



urlpatterns = [
    path('',views.start,name='start'),
    path('index/',views.index,name='index'),
]

Person/urls.py
#!/usr/bin/env python

# -*- encoding: utf-8 -*-

'''
@Author  :   Zhuang_Qingyao
 
@Contact :   qyzhg@163.com
 
@File    :   urls.py
 
@Time    :   2020/5/20 10:23 上午
'''


from django.urls import path

from Person import views


urlpatterns = [
    path('',views.start,name='start'),
    path('index/',views.index,name='index'),                    #首页
    path('person_add/',views.person_add,name='person_add'),     #添加页
    path('person_del/',views.person_del,name='person_del'),     #删除功能
    path('person_edit/',views.person_edit,name='person_edit'),     #修改功能
]

TestPlatform/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Index.urls','Index'),namespace='index')),
    path('person/', include(('Person.urls','Person'),namespace='person')),      #人员管理
    path('project/', include(('Project.urls','Project'),namespace='project')),  #项目管理
    path('pro_inspection/', include(('Pro_inspection.urls','Pro_inspection'),namespace='pro_inspection')),  #项目—视察管理
]

Person/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    person_name = models.CharField(max_length=16)           #人员
    person_is_del = models.BooleanField(default=False)      #逻辑删除
    person_project = models.ManyToManyField('Project.Project')  #多对对关系，关联项目表

Person/views.py
from django.shortcuts import render,HttpResponse,redirect,reverse

# Create your views here.
from Person import models
from Project import models as project_models


def start(request):
    '''
    没写路径的重定向到index
    :param request:
    :return:
    '''
    return redirect(reverse('person:index'))


def index(request):
    '''
    首页
    :param request:
    :return:
    '''
    persons = models.Person.objects.filter(person_is_del=False)
    return render(request,'person/person_list.html',context=locals())


def person_add(request):
    '''
    添加人员
    :param request:
    :return:
    '''
    if request.method == 'GET':
        projects = project_models.Project.objects.filter(project_is_del=False)
        return render(request,'person/person_add.html',context=locals())
    elif request.method == 'POST':
        # 接收表单参数
        person_name = request.POST.get('person_name')           #人员姓名
        project_pk_list = request.POST.getlist('project')       #项目主键(列表）
        #写数据入库
        new_person = models.Person.objects.create(person_name=person_name)
        new_person.person_project.set(project_pk_list)
        return redirect(reverse('person:index'))


def person_del(request):
    '''
    删除人员
    :param request:
    :return:
    '''
    person_pk = request.GET.get('pk')
    person = models.Person
    del_person = person.objects.filter(pk = person_pk).first()
    del_person.person_is_del = True
    del_person.save()
    return redirect(reverse('person:index'))


def person_edit(request):
    '''
    修改人员
    :param request:
    :return:
    '''
    if request.method == 'GET':
        person_pk = request.GET.get('pk')
        person_name = models.Person.objects.filter(pk = person_pk).first().person_name
        person_project = models.Person.objects.filter(pk = person_pk).first().person_project.all()
        all_projects = project_models.Project.objects.filter(project_is_del=False)
        return render(request,'person/person_edit.html',context=locals())
    elif request.method == 'POST':
        #接收数据
        person_pk = request.POST.get('person_pk')
        person_name = request.POST.get('person_name')
        person_projects = request.POST.getlist('projects')
        #更改数据库
        person = models.Person.objects.filter(pk = person_pk).first()
        person.person_name = person_name
        person.person_project.set(person_projects)
        person.save()
        return redirect(reverse('person:index'))

templates/person/person_add.html
{% extends 'person/person_base.html' %}

{% block tabletitle %}
    添加新人员
{% endblock %}

{% block table_person %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">姓名</label>
            <input type="text" class="form-control" id="name" name="person_name" placeholder="请输入姓名">
        </div>
        <div class="form-group">
            <label for="poject">负责项目</label>
            <p>
                {% for project in projects %}
                    <label class="form-group">
                    <input type="checkbox" name="project" value={{ project.pk }}>{{ project.project_name }}
                        &nbsp;
                    </label>
                {% endfor %}
            </p>
        </div>
        <button type="submit" class="btn btn-info">提交</button>
        &nbsp;&nbsp;&nbsp;
        <a href="{% url 'person:index' %}" class="btn btn-warning">返回</a>
    </form>

{% endblock %}

templates/person/person_base.html
{% extends 'base.html' %}

{% block title %}
    测试平台-人员管理
{% endblock %}

{% block body %}
    {#    {{ block.super }}用于获取父模板中block的内容#}



    <div class="panel panel-default" style="overflow:scroll">
        <div class="panel-heading">
            <h3 class="panel-title">
                {% block tabletitle %}
                用户管理
                {% endblock tabletitle %}
            </h3>
        </div>
        <div class="panel-body">
            {% block table_person %}

            {% endblock table_person %}
        </div>
    </div>


{% endblock %}

templates/person/person_edit.html
{% extends 'person/person_base.html' %}

{% block tabletitle %}
    编辑人员
{% endblock %}

{% block table_person %}

    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">姓名</label>
            <input type="text" class="form-control" id="name" name="person_name" value="{{ person_name }}">
        </div>
        <div class="form-group">
            <label for="poject">负责项目</label>
            <p>
                {% for poject in all_projects %}
                    <label class="form-group">
                        <input name="projects" type="checkbox" value="{{ poject.pk }}"
                               {% if poject in person_project %}checked="checked"{% endif %}> {{ poject.project_name }}
                    </label>
                    &nbsp;
                {% endfor %}
            </p>
        </div>
        <input type="text" name="person_pk" value="{{ person_pk }}" style="display: none;" readonly>
        <button type="submit" class="btn btn-info">提交</button>
    </form>

{% endblock %}

templates/person/person_list.html
{% extends 'person/person_base.html' %}

{% block tabletitle %}
    人员列表
{% endblock %}



{% block table_person %}
    {#    {{ block.super }}用于获取父模板中block的内容#}

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>编号</th>
            <th>姓名</th>
            <th>负责项目</th>
            <th>操作</th>
        </tr>
        </thead>

        <tbody>
        {% for person in persons %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ person.person_name }}</td>
                <td>
                    {% for person_project in person.person_project.all %}
                        {% if not person_project.project_is_del  %}

                        {% if forloop.last %}
                            {{ person_project.project_name }}
                        {% else %}
                            {{ person_project.project_name }}，
                        {% endif %}
                        {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <a href="{% url 'person:person_del' %}?pk={{ person.pk }}" class="btn btn-danger btn-sm">删除</a>
                    &nbsp;&nbsp;
                    <a href="{% url 'person:person_edit' %}?pk={{ person.pk }}" class="btn btn-info btn-sm">编辑</a>
                </td>
            </tr>
        {% endfor %}
        </tbody>


    </table>
    <a href="{% url 'person:person_add' %}" class="btn btn-info">添加人员</a>


{% endblock %}