Index/urls.py
#!/usr/bin/env python

# -*- encoding: utf-8 -*-

'''
@Author  :   Zhuang_Qingyao
 
@Contact :   qyzhg@163.com
 
@File    :   urls.py
 
@Time    :   2020/5/20 10:23 上午
'''


from django.urls import path

from Index import views



urlpatterns = [
    path('',views.start,name='start'),
    path('index/',views.index,name='index'),
]

Pro_inspection/urls.py
#!/usr/bin/env python

# -*- encoding: utf-8 -*-

'''
@Author  :   Zhuang_Qingyao
 
@Contact :   qyzhg@163.com
 
@File    :   urls.py
 
@Time    :   2020/5/21 9:02 上午
'''
from django.urls import path

from Pro_inspection import views

urlpatterns = [
    path('', views.start, name='start'),
    path('index/', views.index, name='index'),
    path('state/', views.state, name='state'),
    path('pro_inspection_add/', views.pro_inspection_add, name='pro_inspection_add'),
    path('pro_inspection_del/', views.pro_inspection_del, name='pro_inspection_del'),
    path('pro_inspection_isgrave/', views.pro_inspection_isgrave, name='pro_inspection_isgrave'),
    path('pro_inspection_recycle/', views.pro_inspection_recycle, name='pro_inspection_recycle'),  # 回收站
    path('pro_inspection_restore/', views.pro_inspection_restore, name='pro_inspection_restore'),  # 还原
    #性能测试模块路由
    path('performance_test/', views.performance_test, name='performance_test'),  # 性能测试首页
    path('make_data/', views.make_data, name='make_data'),  # 灌数
]

TestPlatform/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Index.urls','Index'),namespace='index')),
    path('person/', include(('Person.urls','Person'),namespace='person')),      #人员管理
    path('project/', include(('Project.urls','Project'),namespace='project')),  #项目管理
    path('pro_inspection/', include(('Pro_inspection.urls','Pro_inspection'),namespace='pro_inspection')),  #项目—视察管理
]

Pro_inspection/models.py
from django.db import models

# Create your models here.

class InspectionErrors(models.Model):
    '''
    视察问题记录
    '''
    error_name = models.CharField(max_length=256)   #问题名
    state = models.BooleanField(default=True)       #状态
    is_severity = models.BooleanField(default=True) #是否严重
    person = models.ForeignKey('Person.Person',on_delete=models.CASCADE)   #操作人外键
    is_del = models.BooleanField(default=False) #逻辑删除

class MakeData(models.Model):
    '''
    功能菜单
    '''
    name = models.CharField(max_length=256) #模块名

class MakeData_cache(models.Model):
    '''
    假缓存
    '''
    ip = models.CharField(max_length=15)
    port = models.IntegerField(max_length=5)
    username = models.CharField(max_length=64)
    password = models.CharField(max_length=64)
    updata_time = models.DateTimeField(auto_now=True,verbose_name='updata_time')
    last_models = models.ForeignKey(MakeData,on_delete=models.CASCADE)

Pro_inspection/views.py
from django.shortcuts import render,HttpResponse,redirect,reverse
from Person.models import Person
# Create your views here.
from Pro_inspection import models


def index(request):
    '''
    视察首页
    :param request:
    :return:
    '''
    inspection_errors = models.InspectionErrors.objects.filter(is_del=False).order_by('-state')
    return render(request, 'pro_inspection/inspection_index.html',context=locals())


def start(request):
    '''

    :param request:
    :return:
    '''
    return redirect(reverse('pro_inspection:index'))


def state(request):
    '''
    状态修改
    :param request:
    :return:
    '''
    error_pk = request.GET.get('pk')
    error = models.InspectionErrors.objects.filter(pk = error_pk).first()
    if error.state:
        error.state = False
        error.save()
    else:
        error.state = True
        error.save()
    return redirect(reverse('pro_inspection:index'))


def pro_inspection_add(request):
    '''
    添加问题
    :param request:
    :return:
    '''
    if request.method == 'GET':
        all_person = Person.objects.filter(person_is_del=False)
        return render(request,'pro_inspection/inspection_add.html',context=locals())
    elif request.method == 'POST':
        error_name = request.POST.get('error')
        error_person = request.POST.get('person_pk')
        isgrave = request.POST.get('isgrave')#是否严重问题
        if isgrave == 'on':
            isgrave = True
        else:
            isgrave = False
        models.InspectionErrors.objects.create(error_name=error_name,person_id = error_person,is_severity=isgrave)
        return redirect(reverse('pro_inspection:index'))


def pro_inspection_del(request):
    '''
    删除问题
    :param request:
    :return:
    '''
    error_pk = request.GET.get('pk')
    error = models.InspectionErrors.objects.filter(pk = error_pk).first()
    error.is_del = True
    error.save()
    return redirect(reverse('pro_inspection:index'))


def pro_inspection_isgrave(request):
    '''
    移动问题
    :param request:
    :return:
    '''
    error_pk = request.GET.get('pk')
    error = models.InspectionErrors.objects.filter(pk = error_pk).first()
    if error.is_severity:
        error.is_severity = False
        error.save()
    else:
        error.is_severity = True
        error.save()
    return redirect(reverse('pro_inspection:index'))


def pro_inspection_recycle(request):
    '''
    回收站
    :param request:
    :return:
    '''
    if request.method == 'GET':
        del_error = models.InspectionErrors.objects.filter(is_del=True)
        return render(request,'pro_inspection/inspection_recycle.html',context=locals())


def pro_inspection_restore(request):
    '''
    还原回收站
    :param request:
    :return:
    '''
    error_pk = request.GET.get('pk')
    error = models.InspectionErrors.objects.filter(pk=error_pk).first()
    error.is_del = False
    error.save()
    return redirect(reverse('pro_inspection:pro_inspection_recycle'))


def performance_test(request):
    '''
    性能测试入口（工具选择入口）
    :param request:
    :return:
    '''
    return render(request,'pro_inspection/performance_test/performance_test.html')


def make_data(request):
    '''
    灌数
    :param request:
    :return:
    '''
    if request.method == 'GET':
        ip = models.MakeData_cache.objects.all().order_by('-updata_time').first().ip
        port = models.MakeData_cache.objects.all().order_by('-updata_time').first().port
        tool_models = models.MakeData.objects.all()    #所有模块
        last_models = models.MakeData_cache.objects.all().order_by('-updata_time').first().last_models #最后使用模块
        last_username = models.MakeData_cache.objects.all().order_by('-updata_time').first().username
        last_pwd = models.MakeData_cache.objects.all().order_by('-updata_time').first().password
        return render(request,'pro_inspection/performance_test/make_data.html',context=locals())
    elif request.method == 'POST':
        ip = request.POST.get('server_ip')          #目标ip
        port = request.POST.get('server_port')      #目标端口
        model_pk = request.POST.get('mo_pk')        #选择的主键
        data_size = request.POST.get('data_size')   #数据量
        concurrence = request.POST.get('concurrence')#并发量
        username = request.POST.get('uname')
        pwd = request.POST.get('pwd')
        #信息记录到缓存表
        new_cache = models.MakeData_cache
        new_cache.objects.create(
                                ip=ip,
                                port=port,
                                username=username,
                                password=pwd,
                                last_models_id=model_pk
                                )
        return redirect(reverse('pro_inspection:make_data'))

templates/pro_inspection/inspection_add.html
{% extends 'base.html' %}

{% block title %}
    测试平台-视察管理-添加问题
{% endblock %}

{% block body %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">新建问题</h3>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">问题描述</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="error" placeholder="请输入问题描述" name="error">
                    </div>
                </div>

                <div class="form-group">
                    <label for="inputEmail3" class="col-sm-2 control-label">选择测试人员</label>
                    <div class="col-sm-10">
                        {#                        <input type="text" class="form-control" id="error" placeholder="请输入问题描述" name="error">#}
                        <select class="form-control" name="person_pk">

                            {% for person in all_person %}
                                <option value="{{ person.pk }}" name="person_pk">{{ person.person_name }}</option>
                            {% endfor %}


                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="isgrave"> 是否为严重问题
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-default">提交</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/pro_inspection/inspection_index.html
{% extends 'base.html' %}

{% block title %}
    测试平台-视察管理
{% endblock %}

{% block body %}
    <a href="http://10.102.111.117:8092" class="btn btn-primary" target="_blank">许可证管理测试服务器地址>>></a>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'pro_inspection:performance_test' %}" class="btn btn-primary" target="_blank">性能测试地址>>></a>&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="#" class="btn btn-primary" target="_blank">接口测试地址>>></a>&nbsp;&nbsp;&nbsp;&nbsp;
    <hr>

    <!-- ----------------------------------------------------------- -->

    <div class="panel panel-danger">
        <!-- Default panel contents -->
        <div class="panel-heading">严重问题记录</div>

        <!-- Table -->
        <table class="table table-hover">

            <tr style=text-align:center>
                <th nowrap="nowrap" style=text-align:left>编号</th>
                <th nowrap="nowrap" style=text-align:center>问题详情</th>
                <th nowrap="nowrap" style=text-align:center>状态</th>
                <th nowrap="nowrap" style=text-align:center>操作人</th>
                <th nowrap="nowrap" style=text-align:center>操作</th>

            </tr>
            {% for inspection_error in inspection_errors %}
                {% if inspection_error.is_severity %}
                    <td width="5%">{{ inspection_error.pk }}</td>
                    <td width="60%">{{ inspection_error.error_name }}</td>
                    <td width="8%">
                        {% if inspection_error.state %}
                            <a href="{% url 'pro_inspection:state' %}?pk={{ inspection_error.pk }}"
                               class='btn btn-sm btn-danger'>未解决</a>
                        {% else %}
                            <a href="{% url 'pro_inspection:state' %}?pk={{ inspection_error.pk }}"
                               class='btn btn-sm btn-success'>已解决</a>
                        {% endif %}
                    </td>
                    <td width="10%">{{ inspection_error.person.person_name }}</td>
                    <td width="17%">
                        <a href="{% url 'pro_inspection:pro_inspection_del' %}?pk={{ inspection_error.pk }}"
                           class="btn btn-sm btn-warning">删除</a>

                        <a href="{% url 'pro_inspection:pro_inspection_isgrave' %}?pk={{ inspection_error.pk }}" class="btn btn-sm btn-success">移至一般</a>
                    </td>
                {% endif %}
                </tr>
            {% endfor %}


        </table>
    </div>

    <!-- ----------------------------------------------------------- -->

    <div class="panel panel-warning">
        <!-- Default panel contents -->
        <div class="panel-heading">一般问题记录</div>

        <!-- Table -->
        <table class="table table-hover">
            <tr>
                <th nowrap="nowrap" style=text-align:left>编号</th>
                <th nowrap="nowrap" style=text-align:center>问题详情</th>
                <th nowrap="nowrap" style=text-align:center>状态</th>
                <th nowrap="nowrap" style=text-align:center>操作人</th>
                <th nowrap="nowrap" style=text-align:center>操作</th>
            </tr>

            <tr>
                {% for inspection_error in inspection_errors %}
                    {% if not inspection_error.is_severity %}
                        <td width="5%">{{ inspection_error.pk }}</td>
                        <td width="60%">{{ inspection_error.error_name }}</td>
                        <td width="8%">
                            {% if inspection_error.state %}
                                <a href="{% url 'pro_inspection:state' %}?pk={{ inspection_error.pk }}"
                                   class='btn btn-sm btn-danger'>未解决</a>
                            {% else %}
                                <a href="{% url 'pro_inspection:state' %}?pk={{ inspection_error.pk }}"
                                   class='btn btn-sm btn-success'>已解决</a>
                            {% endif %}
                        </td>
                        <td width="10%">{{ inspection_error.person.person_name }}</td>
                        <td width="17%">
                            <a href="{% url 'pro_inspection:pro_inspection_del' %}?pk={{ inspection_error.pk }}"
                               class="btn btn-sm btn-warning">删除</a>
                                                <a href="{% url 'pro_inspection:pro_inspection_isgrave' %}?pk={{ inspection_error.pk }}" class="btn btn-sm btn-danger">移至严重</a>
                        </td>
                    {% endif %}
                    </tr>
                {% endfor %}
        </table>
    </div>
    <a href="{% url  'pro_inspection:pro_inspection_add' %}" class="btn btn-info btn-sm">添加问题</a>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'pro_inspection:pro_inspection_recycle' %}" class="btn btn-warning btn-sm">回收站</a>
{% endblock %}

templates/pro_inspection/inspection_recycle.html
{% extends 'base.html' %}

{% block title %}
    测试平台-许可证管理-回收站
{% endblock %}

{% block body %}
    {#    {{ block.super }}用于获取父模板中block的内容#}

    <a href="http://10.102.111.117:8092" class="btn btn-primary" target="_blank">许可证管理测试服务器地址>>></a>
    &nbsp;&nbsp;&nbsp;&nbsp;
    <a href="#" class="btn btn-primary" target="_blank">性能测试地址>>></a>&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="#" class="btn btn-primary" target="_blank">接口测试地址>>></a>&nbsp;&nbsp;&nbsp;&nbsp;
    <hr>

    <!-- ----------------------------------------------------------- -->




    <div class="panel panel-info">
        <!-- Default panel contents -->
        <div class="panel-heading">回收站</div>

        <!-- Table -->
        <table class="table table-hover">

            <tr>

                <th nowrap="nowrap" style=text-align:center>问题详情</th>
                <th nowrap="nowrap" style=text-align:center>状态</th>
                <th nowrap="nowrap" style=text-align:center>严重程度</th>
                <th nowrap="nowrap" style=text-align:center>操作人</th>
                {#                <th>创建时间</th>#}
                <th nowrap="nowrap" style=text-align:center>操作</th>


            </tr>
            {% for error in del_error %}
                <tr>
                    <td>{{ error.error_name }}</td>
                    {% if error.state %}
                        {#                            <td><span class="label label-success">已解决</span></td>#}
                        <td nowrap="nowrap">
                            <div class="btn btn-success btn-sm">已解决</div>
                        </td>
                    {% else %}
                        {#                            <td><span class="label label-danger">未解决</span></td>#}
                        <td nowrap="nowrap">
                            <div class="btn btn-danger btn-sm">未解决</div>
                        </td>
                    {% endif %}
                    <td nowrap="nowrap">
                        {% if error.is_severity %}
                            <div class="btn btn-sm btn-warning">严重</div>
                        {% else %}
                            <div class="btn btn-sm btn-info">一般</div>
                        {% endif %}

                    </td>

                    <td nowrap="nowrap">{{ error.person.person_name }}</td>
                    {#                        <td>{{ foo.creattime }}</td>#}
                    <td>


                        <a href="{% url 'pro_inspection:pro_inspection_restore' %}?pk={{ error.pk }}" class="btn btn-primary btn-sm">还原</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <a href="{% url 'pro_inspection:index' %}" class="btn btn-warning">返回</a>



{% endblock %}