Index/urls.py
#!/usr/bin/env python

# -*- encoding: utf-8 -*-

'''
@Author  :   Zhuang_Qingyao
 
@Contact :   qyzhg@163.com
 
@File    :   urls.py
 
@Time    :   2020/5/20 10:23 上午
'''


from django.urls import path

from Index import views



urlpatterns = [
    path('',views.start,name='start'),
    path('index/',views.index,name='index'),
]

Project/urls.py
#!/usr/bin/env python

# -*- encoding: utf-8 -*-

'''
@Author  :   Zhuang_Qingyao
 
@Contact :   qyzhg@163.com
 
@File    :   urls.py
 
@Time    :   2020/5/20 10:42 上午
'''


from django.urls import path

from Project import views


urlpatterns = [
    path('',views.start,name='start'),
    path('index/',views.index,name='index'),
    path('project_add/',views.project_add,name='project_add'),
    path('project_del/',views.project_del,name='project_del'),
    path('project_edit/',views.project_edit,name='project_edit'),
]

TestPlatform/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Index.urls','Index'),namespace='index')),
    path('person/', include(('Person.urls','Person'),namespace='person')),      #人员管理
    path('project/', include(('Project.urls','Project'),namespace='project')),  #项目管理
    path('pro_inspection/', include(('Pro_inspection.urls','Pro_inspection'),namespace='pro_inspection')),  #项目—视察管理
]

Person/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    person_name = models.CharField(max_length=16)           #人员
    person_is_del = models.BooleanField(default=False)      #逻辑删除
    person_project = models.ManyToManyField('Project.Project')  #多对对关系，关联项目表

Project/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    project_name = models.CharField(max_length=128)
    project_is_del = models.BooleanField(default=False)

Project/views.py
from django.shortcuts import render,HttpResponse,redirect,reverse

# Create your views here.
from Project import models
from Person import models as person_models


def start(request):
    return redirect(reverse('project:index'))


def index(request):
    all_projects = models.Project.objects.filter(project_is_del=False)
    return render(request,'project/project_list.html',context=locals())


def project_add(request):
    if request.method == 'GET':
        all_person = person_models.Person.objects.filter(person_is_del=False)
        return render(request,'project/project_add.html',context=locals())
    elif request.method == 'POST':
        project_name = request.POST.get('project_name')
        project_persons = request.POST.getlist('persons')
        new_project = models.Project.objects.create(project_name=project_name)
        new_project.person_set.set(project_persons)
        return redirect(reverse('project:index'))


def project_del(request):
    project_pk = request.GET.get('pk')
    project = models.Project.objects.filter(pk = project_pk).first()
    project.project_is_del = True
    project.save()
    return redirect(reverse('project:index'))


def project_edit(request):
    if request.method == 'GET':
        project_pk = request.GET.get('pk')
        project = models.Project.objects.filter(pk = project_pk).first()
        all_person = person_models.Person.objects.filter(person_is_del=False)
        project_person = project.person_set.all()
        return render(request,'project/project_edit.html',context=locals())

    if request.method == 'POST':
        project_pk = request.POST.get('project_pk')

templates/project/project_add.html
{% extends 'project/project_base.html' %}

{% block tabletitle %}
    添加新项目
{% endblock %}

{% block table_project %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="name">项目名称</label>
            <input type="text" class="form-control" id="name" name="project_name" placeholder="请输入项目名称">
        </div>
        <div class="form-group">
            <label for="poject">项目负责人</label>
            <p>
                {% for person in all_person %}
                    <label class="form-group">
                        <input name="persons" type="checkbox" value="{{ person.pk }}"/> {{ person.person_name }}
                    </label>&nbsp;
                {% endfor %}
            </p>
        </div>
        <button type="submit" class="btn btn-info">提交</button>
    </form>
{% endblock %}

templates/project/project_base.html
{% extends 'base.html' %}

{% block title %}
    测试平台-项目管理
{% endblock %}

{% block body %}
    {#    {{ block.super }}用于获取父模板中block的内容#}



    <div class="panel panel-default" style="overflow:scroll">
        <div class="panel-heading">
            <h3 class="panel-title">
                {% block tabletitle %}
                项目管理
                {% endblock tabletitle %}
            </h3>
        </div>
        <div class="panel-body">
            {% block table_project %}

            {% endblock table_project %}
        </div>
    </div>


{% endblock %}

templates/project/project_edit.html
{% extends 'project/project_base.html' %}

{% block tabletitle %}
    编辑项目
{% endblock %}

{% block table_project %}
    <form method="post">
        <div class="form-group">
            <label for="name">项目名称</label>
            <input type="name" class="form-control" id="name" name="name" value="{{ project.project_name}}">
        </div>
        <div class="form-group">
            <label for="poject">项目负责人</label>

            <p>
                {% for person in all_person %}
                    <label class="form-group"><input name="persons" type="checkbox" value="{{ person.pk }}"
                            {% if person in project_person %} checked="checked"{% endif %}
                    /> {{ person.person_name }} </label>&nbsp;
                {% endfor %}
            </p>


        </div>

        <input type="text" value="{{ project_pk }}" readonly style="display: none;" name="project_pk">
        <button type="submit" class="btn btn-info">提交</button>
    </form>




{% endblock %}

templates/project/project_list.html
{% extends 'project/project_base.html' %}

{% block tabletitle %}
    项目列表
{% endblock %}



{% block table_project %}

    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>编号</th>
            <th>项目名称</th>
            <th>负责人</th>
            <th>操作</th>
        </tr>
        </thead>

        <tbody>
        <tr>

            {% for project in all_projects %}

                <td>{{ forloop.counter }}</td>
                <td>{{ project.project_name }}</td>

                <td>
                    {% for person in project.person_set.all %}
                        {% if not person.person_is_del%}

                        {% if forloop.last %}
                            {{person.person_name}}
                            {% else %}
                            {{person.person_name}}，
                        {% endif %}
                        {% endif %}
                    {% endfor %}
                </td>

                <td><a href="{% url 'project:project_del' %}?pk={{ project.pk }}" class="btn btn-danger btn-sm">删除</a>
                    &nbsp;&nbsp;
                    <a href="{% url 'project:project_edit' %}?pk={{ project.pk }}" class="btn btn-info btn-sm">编辑</a>

                </tr>
            {% endfor %}
        </tbody>

    </table>
    <a href="{% url 'project:project_add' %}" class="btn btn-info">添加项目</a>

{% endblock %}